package stringfromjava;

public class CountWordInString {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		
		String s = "         TODO Autogenerated method stub         ";
		s = s.trim();
		String[] arr = s.split(" ");
		System.out.println(arr.length);
		
		String s1 = "         TODO     Auto-generated                   method                         stub         ";
		s1 = s1.replaceAll("\\s+", " ");
		int count = 0;
		for(int i = 0;i<s1.length()-1;i++) {
			if(s1.charAt(i)==' ' && s1.charAt(i+1)!=' ') {         //                         1st space and second should not space
				count++;
			}
			
		}
		
		System.out.println(count);
	}

}
