package stringfromjava;

public class ReverseEachWordAndWholeString {

	public static void main(String[] args) {
		// TODO Auto-generated method stub

		
		String s = "TODO Autogenerated method stub";
		String revString = "";
		for(int i = s.length()-1;i>=0;i--) {
			revString = revString+s.charAt(i);
		}
		
		System.out.println(revString);
	}

}
