package stringfromjava;

public class ReverseWordsFromString {

	public static void main(String[] args) {
		// TODO Autogenerated method stub

		String s = "TODO Autogenerated method stub";
		String[] sarr = s.split(" ");   // sarr = {"TODO","Autogenerated","method","stub"}
		String output = "";
		
		for(int i = 0;i<sarr.length;i++) {
			String word = sarr[i]; // TODO
			String revWord ="";
			for(int j = word.length()-1;j>=0;j--) {
				revWord = revWord +word.charAt(j);
			}
			
			output =output+revWord+" ";
			
		}
		
		System.out.println(output.trim());
		
		
		
	}

}
